SW-API/Models/ErrorViewModel.cs
using System;

namespace SW_API.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SW-API/Models/People.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SW_API.Models
{
    public class People
    {
        public string Name { get; set; }
        public string Height { get; set; }
        public string Mass { get; set; }
        public string Hair_Color { get; set; }
        public string Skin_Color { get; set; }
        public string Eye_Color { get; set; }
        public string Birth_Year { get; set; }
        public string Gender { get; set; }
        public string Homeworld { get; set; }

        public string[] Films { get; set; }
        public string[] Vehicles { get; set; }
        public string[] Starships { get; set; }
    }
}

SW-API/Models/Planet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SW_API.Models
{
    public class Planet
    {
        public string Name { get; set; }
        public string Rotation_Period { get; set; }
        public string Orbital_Period { get; set; }
        public string Diameter { get; set; }
        public string Climate { get; set; }
        public string Gravity { get; set; }
        public string Terrain { get; set; }
        public string Surface_Water { get; set; }
        public string Population { get; set; }

        public string[] Residents { get; set; }

        public string[] Films { get; set; }

    }
}

SW-API/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SW_API.Models;

namespace SW_API.Controllers
{
    public class HomeController : Controller
    {

        public async Task<IActionResult> Index()

        {
            return View();
        }

        

    }
}

SW-API/Controllers/StarWarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SW_API.Models;

namespace SW_API.Controllers
{
    public class StarWarsController : Controller
    {
        public IActionResult Index() // add view
        {
            return View();
        }
        public async Task<IActionResult> GetPersonById(int id)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://swapi.co/api/");
            //client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (compatible; GrandCircus/1.0)");

            var response = await client.GetAsync($"people/{id}");
            var person = await response.Content.ReadAsAsync<People>();

            return View(person);
        }


        public async Task<IActionResult> GetPlanetById(int id)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://swapi.co/api/");
            //client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (compatible; GrandCircus/1.0)");

            var response = await client.GetAsync($"planets/{id}");
            var planet = await response.Content.ReadAsAsync<Planet>();

            return View(planet);
        }
    }
}

SW-API/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SW-API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SW_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SW_API</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StarWars" asp-action="Index">Star Wars Stuff</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SW_API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SW-API/Views/StarWars/GetPersonById.cshtml
@{
    ViewData["Title"] = "GetPersonById";
}

@model People

<h1>Character and Stuff</h1>

@Model.Name

<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Height</th>
        <td>@Model.Height</td>
    </tr>
    <tr>
        <th>Weight</th>
        <td>@Model.Mass</td>
    </tr>
    <tr>
        <th>Homeworld</th>
        <td>@Model.Homeworld</td>

    </tr>
    <tr>
        <th>Favorite Vehicles:</th>
        <td>
            @foreach (string vehicle in Model.Vehicles)
            {
                <div>@vehicle</div>
            }
        </td>
    </tr>
    <tr>
        <th>Appears in:</th>
        <td>
            @foreach (string appaerance in Model.Films)
            {
                <div>@appaerance</div>

            }
        </td>
    </tr>

</table>

SW-API/Views/StarWars/GetPlanetById.cshtml
@{
    ViewData["Title"] = "GetPlanetById";
}



@model Planet

<h1>Planets</h1>


<table class="table table-dark">
    <tr>
        <th>Name</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Rotational Period</th>
        <td>@Model.Rotation_Period Days</td>
    </tr>
    <tr>
        <th>Orbital Period</th>
        <td>@Model.Orbital_Period Orbital Time</td>
    </tr>
    <tr>
        <th>Climate</th>
        <td>@Model.Climate</td>
    </tr>
    <tr>
        <th>Population</th>
        <td>@Model.Population</td>
    </tr>
    <tr>
        <th>Residents</th>
        <td>
            @foreach (string residents in Model.Residents)
            {
                <div>@residents</div>
            }
        </td>
    </tr>


</table>

SW-API/Views/StarWars/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Star Wars</h1>

<div class="form-group">
    <form action="../StarWars/GetPersonById" method="post" class="form-group">
        Character: <input type="search" name="id" aria-describedby ="searchHelp" value="" placeholder="Please enter a number" class="form-control form-control-lg"/><br/>
    <medium id="searchHelp" class="form-text text-muted">Use the Force!</medium>
        <input type="submit" name="submit" value="submit" class="btn btn-light" />
    
</form>
    <form action="../StarWars/GetPlanetById" method="post">
        Planet: <input type="search" name="id" value="" aria-describedby ="searchHelp" placeholder="Please enter a number" class="form-control form-control-lg" /><br />
        <medium id="searchHelp" class="form-text text-muted">Your Anger Makes You Stronger!</medium>
        <input type="submit" name="submit" value="submit" class="btn btn-dark" />
    </form>
</div>